spring.datasource.url=jdbc:postgresql://localhost:5432/rideJournal
spring.datasource.username=rideJournal
spring.datasource.password=rideJournal

#debug=true

jwt.secret=${SNACKBOX_JWT_SECRET:JCwB2tfvf4iuQfheqE6Slc4eQfUDRf9hu7ifGdMJFiV}
# expiry in milliseconds
jwt.expiry=${SNACKBOX_JWT_EXPIRY:86400000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_URL:true}

logging.level.org.springframework.security=TRACE

# use this later to generate DDL scripts for production when ready to deploy
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql
