spring.datasource.url=jdbc:postgresql://localhost:5432/rideJournal
spring.datasource.username=rideJournal
spring.datasource.password=rideJournal

#debug=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_URL:true}

# use this later to generate DDL scripts for production when ready to deploy
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql
